-- SQLPracticePro — StreamFlix Schema (v2)
-- Scope: Movies, Genres, Directors only. Reviews is intentionally excluded
-- until a later ticket set needs it (see docs/PROJECT_BRIEF.md).
-- Engine target: PostgreSQL 14+

-- Drop order matters: children before parents, since movies references
-- both genres and directors.
DROP TABLE IF EXISTS movies;
DROP TABLE IF EXISTS genres;
DROP TABLE IF EXISTS directors;

-- ---------------------------------------------------------------------
-- genres
-- ---------------------------------------------------------------------
CREATE TABLE genres (
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE
);

COMMENT ON TABLE genres IS 'Movie genres (Action, Drama, etc). One row per genre.';

-- ---------------------------------------------------------------------
-- directors
-- ---------------------------------------------------------------------
CREATE TABLE directors (
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    TEXT NOT NULL,
    country TEXT NOT NULL
);

COMMENT ON TABLE directors IS 'Directors credited on StreamFlix catalog movies.';

-- ---------------------------------------------------------------------
-- movies
-- ---------------------------------------------------------------------
CREATE TABLE movies (
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title            TEXT NOT NULL UNIQUE,
    genre_id         INTEGER NOT NULL REFERENCES genres(id) ON DELETE RESTRICT,
    director_id      INTEGER NOT NULL REFERENCES directors(id) ON DELETE RESTRICT,
    release_year     INTEGER NOT NULL CHECK (release_year BETWEEN 1888 AND 2100),

    -- Nullable by design — see database/README.md for the reasoning
    -- behind every one of these.
    rating           NUMERIC(3,1) CHECK (rating BETWEEN 0 AND 10),
    duration_minutes INTEGER CHECK (duration_minutes > 0),
    language         TEXT,
    country          TEXT
);

COMMENT ON TABLE movies IS 'StreamFlix catalog. Every title currently available to stream.';

-- Postgres does not index foreign key columns automatically, and upcoming
-- tickets will JOIN movies to genres/directors frequently — these keep
-- those joins fast as the catalog grows.
CREATE INDEX idx_movies_genre_id ON movies (genre_id);
CREATE INDEX idx_movies_director_id ON movies (director_id);
